export const FETCH_FOODS_REQUEST = 'FETCH_FOODS_REQUEST';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAIL = 'FETCH_FOODS_FAIL';

export const FETCH_FOOD_REQUEST = 'FETCH_FOOD_REQUEST';
export const FETCH_FOOD_SUCCESS = 'FETCH_FOOD_SUCCESS';
export const FETCH_FOOD_FAIL = 'FETCH_FOOD_FAIL';

export const FETCH_FOOD_TYPES_REQUEST = 'FETCH_FOOD_TYPES_REQUEST';
export const FETCH_FOOD_TYPES_SUCCESS = 'FETCH_FOOD_TYPES_SUCCESS';
export const FETCH_FOOD_TYPES_FAIL = 'FETCH_FOOD_TYPES_FAIL';

export const ADD_FOOD_REQUEST = 'ADD_FOOD_REQUEST';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAIL = 'ADD_FOOD_FAIL';

export const UPDATE_FOOD_REQUEST = 'UPDATE_FOOD_REQUEST';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_FAIL = 'UPDATE_FOOD_FAIL';

export const DELETE_FOOD_REQUEST = 'DELETE_FOOD_REQUEST';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_FAIL = 'DELETE_FOOD_FAIL';

export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';

export const FETCH_RECIPE_REQUEST = 'FETCH_RECIPE_REQUEST';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL';

export const ADD_RECIPE_REQUEST = 'ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAIL = 'ADD_RECIPE_FAIL';

export const UPDATE_RECIPE_REQUEST = 'UPDATE_RECIPE_REQUEST';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL';

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';

export const FETCH_PLANS_REQUEST = 'FETCH_PLANS_REQUEST';
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS';
export const FETCH_PLANS_FAIL = 'FETCH_PLANS_FAIL';

export const ADD_PLAN_REQUEST = 'ADD_PLAN_REQUEST';
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAIL = 'ADD_PLAN_FAIL';

export const UPDATE_PLAN_REQUEST = 'UPDATE_PLAN_REQUEST';
export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAIL = 'UPDATE_PLAN_FAIL';

export const DELETE_PLAN_REQUEST = 'DELETE_PLAN_REQUEST';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAIL = 'DELETE_PLAN_FAIL';

export const SHOW_INSERT_FOOD_MODAL = 'SHOW_ADD_FOOD_MODAL';
export const HIDE_INSERT_FOOD_MODAL = 'HIDE_ADD_FOOD_MODAL';

export const SHOW_EDIT_FOOD_MODAL = 'SHOW_EDIT_FOOD_MODAL';
export const HIDE_EDIT_FOOD_MODAL = 'HIDE_EDIT_FOOD_MODAL';

export const SHOW_DELETE_FOOD_MODAL = 'SHOW_DELETE_FOOD_MODAL';
export const HIDE_DELETE_FOOD_MODAL = 'HIDE_DELETE_FOOD_MODAL';

export const SHOW_RECIPE_MODAL = 'SHOW_RECIPE_MODAL';
export const HIDE_RECIPE_MODAL = 'HIDE_RECIPE_MODAL';

export const SHOW_INSERT_RECIPE_MODAL = 'SHOW_ADD_RECIPE_MODAL';
export const HIDE_INSERT_RECIPE_MODAL = 'HIDE_ADD_RECIPE_MODAL';

export const SHOW_EDIT_RECIPE_MODAL = 'SHOW_EDIT_RECIPE_MODAL';
export const HIDE_EDIT_RECIPE_MODAL = 'HIDE_EDIT_RECIPE_MODAL';

export const SHOW_DELETE_RECIPE_MODAL = 'SHOW_DELETE_RECIPE_MODAL';
export const HIDE_DELETE_RECIPE_MODAL = 'HIDE_DELETE_RECIPE_MODAL';