export const FETCH_FOODS_REQUEST = 'FETCH_FOODS_REQUEST';
export const FETCH_FOODS_SUCCESS = 'FETCH_FOODS_SUCCESS';
export const FETCH_FOODS_FAIL = 'FETCH_FOODS_FAIL';

export const FETCH_FOOD_REQUEST = 'FETCH_FOOD_REQUEST';
export const FETCH_FOOD_SUCCESS = 'FETCH_FOOD_SUCCESS';
export const FETCH_FOOD_FAIL = 'FETCH_FOOD_FAIL';

export const FETCH_FOOD_TYPES_REQUEST = 'FETCH_FOOD_TYPES_REQUEST';
export const FETCH_FOOD_TYPES_SUCCESS = 'FETCH_FOOD_TYPES_SUCCESS';
export const FETCH_FOOD_TYPES_FAIL = 'FETCH_FOOD_TYPES_FAIL';

export const ADD_FOOD_REQUEST = 'ADD_FOOD_REQUEST';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAIL = 'ADD_FOOD_FAIL';

export const UPDATE_FOOD_REQUEST = 'UPDATE_FOOD_REQUEST';
export const UPDATE_FOOD_SUCCESS = 'UPDATE_FOOD_SUCCESS';
export const UPDATE_FOOD_FAIL = 'UPDATE_FOOD_FAIL';

export const DELETE_FOOD_REQUEST = 'DELETE_FOOD_REQUEST';
export const DELETE_FOOD_SUCCESS = 'DELETE_FOOD_SUCCESS';
export const DELETE_FOOD_FAIL = 'DELETE_FOOD_FAIL';

export const FETCH_MEALS_REQUEST = 'FETCH_MEALS_REQUEST';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAIL = 'FETCH_MEALS_FAIL';

export const FETCH_MEAL_REQUEST = 'FETCH_MEAL_REQUEST';
export const FETCH_MEAL_SUCCESS = 'FETCH_MEAL_SUCCESS';
export const FETCH_MEAL_FAIL = 'FETCH_MEAL_FAIL';

export const ADD_MEAL_REQUEST = 'ADD_MEAL_REQUEST';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAIL = 'ADD_MEAL_FAIL';

export const UPDATE_MEAL_REQUEST = 'UPDATE_MEAL_REQUEST';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAIL = 'UPDATE_MEAL_FAIL';

export const DELETE_MEAL_REQUEST = 'DELETE_MEAL_REQUEST';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAIL = 'DELETE_MEAL_FAIL';
